### ISSUE TITLE
Custom layout

### ISSUE THREAD

**Issue by rEnr3n** [SSilence/selfoss#1080]
selfoss v2.18

By default, 3 columns are created when reading a long article. I find it inconvenient. The suggestion here, https://github.com/SSilence/selfoss/issues/629#issuecomment-157969443, does not seem to work. Please add an option to customize it.

**Comment by niol** [comment]
I use the following in `user.css` which works well:
```css
.entry-content {
    -moz-column-count: 1;
    -webkit-column-count: 1;
    column-count: 1;
    max-width: 750px;
}
```
