### ISSUE TITLE
Show number of unread items in nav for sources with long name

### ISSUE THREAD

**Issue by lapete** [SSilence/selfoss#1085]
In the list of feeds, the feeds with unread articles are bold and followed by the number of unread articles. But if the name of the feed is too long, together with the number it sometimes exceeds the with of the list. 
I would suggest to set the number at the beginning instead of the end, so that it's still visible, while only a part of the name is cut.

**Comment by jtojnar** [comment]
Or maybe we could apply something like this:

```css
#nav-sources li {
  display: flex;
}
#nav-sources li .nav-source {
  text-overflow: ellipsis;
  min-width: 0;
  overflow: hidden;
  margin-right: 0.25em;
}
```

![screen shot 2019-01-28 at 23 38 51](https://user-images.githubusercontent.com/705123/51871195-ff10e380-2355-11e9-80fb-35f84df13883.png)
