### ISSUE TITLE
Feature Request: Single colum reading

### ISSUE THREAD

**Issue by TobiasDev** [SSilence/selfoss#1167]
I really like how I can read full articles directly with full RSS feeds. However, I'm struggling a bit to read it in the web version currently because of the column splitting. Is there any way to change the three columns to just a single column that is longer?

**Comment by jtojnar** [comment]
This has been fixed in https://github.com/SSilence/selfoss/pull/1081 by only using multiple columns for short articles. You can fetch the [development build](https://github.com/SSilence/selfoss#download) to try it.

Alternately, you can add the following block into `user.css` file in the selfoss root directory. That should force a single column in all cases:

```css
.entry-content {
    column-count: 1 !important;
    max-width: 750px;
    margin: auto;
}
```
