### ISSUE TITLE
Collapse menu items based on config file

### ISSUE THREAD

**Issue by breadcat** [SSilence/selfoss#1217]
I rarely use the 'Filter' category in the sidebar (Newest, Unread, Starred) so would prefer it to be collapsed by default. With this collapsed, it gives more space for Tags, which makes sense on smaller vertical height screens.

I understand this is probably a niche option, so it would make sense to be a config file option instead of a default.

**Comment by jtojnar** [comment]
You can make it collapse after start by creating a `user.js` file in your selfoss directory and placing the following code inside:

```javascript
if (!['hashpasswordbody', 'opmlbody'].includes(document.body.getAttribute('id'))) {
	document.getElementById('nav-filter-title').click()
}
```

If you never want to use the option, you can put the following into `user.css` in your selfoss directory:

```css
#nav-filter-wrapper, #nav-filter-wrapper + .separator {
	display: none;
}

#nav-tags-title {
	margin-top: 20px;
}
```

These work for the [latest build of selfoss](https://github.com/SSilence/selfoss#download), if you use 2.18, I can try to adapt the code.
